server {
    listen $PORT;
    root /app/packages/frontend/dist;
    index index.html;

    location /api/ {
        proxy_pass https://backend-production-ecce.up.railway.app/api/;
        proxy_set_header Host backend-production-ecce.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
