[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm", "nginx", "gettext"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter frontend build"]

[start]
cmd = "nginx -g 'daemon off;'"
