[build]
builder = "nixpacks"

[deploy]
startCommand = "envsubst '$PORT' < /app/packages/frontend/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
restartPolicyType = "on_failure"
