[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter backend build",
  "cp -r src/db/migrations dist/db/migrations"
]

[start]
cmd = "node dist/index.js"

